FROM ubuntu:latest
RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install curl git libssl-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev
RUN apt-get -y install libreadline6 libreadline6-dev build-essential
